
-- Criação da tabela ESTUDANTES
CREATE TABLE USR_GESTAO_ACAD.ESTUDANTES (
    ESTUDANTE_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE,
    MATRICULA VARCHAR2(20),
    CURSO_ID NUMBER,
    PRIMARY KEY (ESTUDANTE_ID),
    FOREIGN KEY (CURSO_ID) REFERENCES USR_GESTAO_ACAD.CURSOS (CURSO_ID)
);

-- Criação da tabela CURSOS
CREATE TABLE USR_GESTAO_ACAD.CURSOS (
    CURSO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO CLOB,
    DURACAO NUMBER,
    PRIMARY KEY (CURSO_ID)
);

-- Criação da tabela PROFESSORES
CREATE TABLE USR_GESTAO_ACAD.PROFESSORES (
    PROFESSOR_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DEPARTAMENTO VARCHAR2(100),
    PRIMARY KEY (PROFESSOR_ID)
);

-- Criação da tabela DISCIPLINAS
CREATE TABLE USR_GESTAO_ACAD.DISCIPLINAS (
    DISCIPLINA_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CURSO_ID NUMBER,
    PROFESSOR_ID NUMBER,
    PRIMARY KEY (DISCIPLINA_ID),
    FOREIGN KEY (CURSO_ID) REFERENCES USR_GESTAO_ACAD.CURSOS (CURSO_ID),
    FOREIGN KEY (PROFESSOR_ID) REFERENCES USR_GESTAO_ACAD.PROFESSORES (PROFESSOR_ID)
);

-- Criação da tabela MATRICULAS
CREATE TABLE USR_GESTAO_ACAD.MATRICULAS (
    MATRICULA_ID NUMBER NOT NULL,
    ESTUDANTE_ID NUMBER NOT NULL,
    DISCIPLINA_ID NUMBER NOT NULL,
    DATA_MATRICULA DATE,
    PRIMARY KEY (MATRICULA_ID),
    FOREIGN KEY (ESTUDANTE_ID) REFERENCES USR_GESTAO_ACAD.ESTUDANTES (ESTUDANTE_ID),
    FOREIGN KEY (DISCIPLINA_ID) REFERENCES USR_GESTAO_ACAD.DISCIPLINAS (DISCIPLINA_ID)
);
